language: python
sudo: false
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "pypy"

branches:
  only:
    - master
    - development

install:
  - travis_retry pip install -Ur requirements-dev.txt
  - if [[ $TRAVIS_PYTHON_VERSION == 'pypy' ]] || [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then travis_retry pip install enum34 typing ; fi

script:
  - py.test tests/ --cov=pyapp

after_success:
  - bash <(curl -s https://codecov.io/bash)
